name: GITHUB action CICD
on:
  workflow_dispatch:
jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v7
      - name: setup java 21
      - uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: buid project with maven
        run: mvn clean install
